/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/config': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取配置信息 */
    get: operations['config.index'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/account/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按 forgeHost+username 删除 account */
    post: operations['forge.accountDelete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/account/fetch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 拉取 account 名下全部远端仓库 */
    post: operations['forge.accountFetch'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/account/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取 forge account 列表（token 打码） */
    get: operations['forge.accountList'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/account/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按键（host/username）重排 account 顺序 */
    post: operations['forge.accountReorder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/account/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增或按 forgeHost+username 替换 account */
    post: operations['forge.accountSave'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按 host 删除 forge */
    post: operations['forge.delete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取 forge 列表 */
    get: operations['forge.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/overview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** forge 页聚合：全部 account 对账行 + 拉取元信息（只读缓存不外呼） */
    get: operations['forge.overview'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按 host 重排 forge 顺序 */
    post: operations['forge.reorder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/forge/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增或按 host 替换 forge */
    post: operations['forge.save'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/icon/extract': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 从本地路径（.app 目录或图片文件）或 http(s) URL 提取图标（64px PNG，base64） */
    post: operations['icon.extract'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/md/content': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 读取 markdown 文件原文 */
    get: operations['md.content'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/md/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出目录下的 markdown 文件 */
    get: operations['md.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按名删除 opener */
    post: operations['opener.delete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/diff-open': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用指定 opener 对比两个路径（diff-dir/diff-file） */
    post: operations['opener.diffOpen'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/intent-default/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 清除某 intent 的默认 opener */
    post: operations['opener.intentDefaultDelete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/intent-default/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 设置某 intent 的默认 opener */
    post: operations['opener.intentDefaultSave'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/intents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取打开意图清单（intent → 默认 opener + 候选） */
    get: operations['opener.intents'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取 opener 列表 */
    get: operations['opener.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/open': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用指定 opener 打开任意文件或目录 */
    post: operations['opener.open'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按名重排 opener 顺序 */
    post: operations['opener.reorder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/opener/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增或更新 opener（按 name 替换） */
    post: operations['opener.save'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/clone-rule/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按 host+prefix 删除 clone 规则 */
    post: operations['project.cloneRuleDelete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/clone-rule/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按键重排 clone 规则顺序 */
    post: operations['project.cloneRuleReorder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/clone-rule/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增或按 host+prefix 替换 clone 规则 */
    post: operations['project.cloneRuleSave'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/clone-rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取 clone 规则 */
    get: operations['project.cloneRules'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取项目列表 */
    get: operations['project.list'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/open': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 用指定 opener 打开已收录项目（记 usage；目标目录选择为 1030/1032 预留） */
    post: operations['project.open'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/scan-rule/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按 path 删除扫描规则 */
    post: operations['project.scanRuleDelete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/scan-rule/reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 按 path 重排扫描规则顺序 */
    post: operations['project.scanRuleReorder'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/scan-rule/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增或按 path 替换扫描规则 */
    post: operations['project.scanRuleSave'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/scan-rules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取扫描规则 */
    get: operations['project.scanRules'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/workspace/get': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取项目 workspace 状态（生效清单 / 显式声明 / 探测候选） */
    get: operations['project.workspaceGet'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/project/workspace/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 保存显式 workspaces 声明（.cube/cube.json）并即时重采集 */
    post: operations['project.workspaceSave'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/system/whoami': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 服务身份探活 */
    get: operations['system.whoami'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usage/recent-paths': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取最近使用的路径清单（去重取最新，最近使用倒序） */
    get: operations['usage.recentPaths'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/usage/record': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 补记一条使用记录（web 直开不经过后端记录的场景，如 url 型 opener 动作、workbench 进入） */
    post: operations['usage.record'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/branch/add': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新建本地分支（不检出） */
    post: operations['workbench.branchAdd'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/branch/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 删除本地分支 */
    post: operations['workbench.branchDelete'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/changes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出源相对上一版本的变更文件 */
    get: operations['workbench.changes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/commit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取 TreeSource（ref/commit）指向提交的完整信息 */
    get: operations['workbench.commit'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/commits': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 拉取工作台 commit 图（分页） */
    get: operations['workbench.commits'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/diff': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 双 TreeSource 目录级对比 */
    get: operations['workbench.diff'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/file': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 读取 TreeSource 下的文件内容 */
    get: operations['workbench.file'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/file-diff': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 双 TreeSource 单文件 diff */
    get: operations['workbench.fileDiff'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/file/raw': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 读取文件原始内容 */
    get: operations['workbench.fileRaw'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/file/save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 保存工作副本文件（唯一写路径） */
    post: operations['workbench.fileSave'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/info': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取工作台仓库信息 */
    get: operations['workbench.info'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/refs': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取工作台分支与tag列表 */
    get: operations['workbench.refs'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/remotes': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 获取工作台 remote 列表 */
    get: operations['workbench.remotes'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/tree': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 列出 TreeSource 下的目录树 */
    get: operations['workbench.tree'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/worktree/add': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 新增 worktree */
    post: operations['workbench.worktreeAdd'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/worktree/prune': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 清理失效的 worktree 管理记录 */
    post: operations['workbench.worktreePrune'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/worktree/remove': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 删除 worktree（非 force 预检拒绝返回 denied+reasons） */
    post: operations['workbench.worktreeRemove'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/worktree/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** 重置 worktree 到指定分支/commit（可选 hard） */
    post: operations['workbench.worktreeReset'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/workbench/worktrees': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** 全部工作副本的状态快照 */
    get: operations['workbench.worktrees'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Account: {
      forgeHost: string;
      token: string;
      username: string;
    };
    AccountDeleteInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AccountDeleteInputBody.json
       */
      readonly $schema?: string;
      forgeHost: string;
      username: string;
    };
    AccountFetchInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AccountFetchInputBody.json
       */
      readonly $schema?: string;
      /** @description 跳过缓存强制重拉 */
      force?: boolean;
      forgeHost: string;
      username: string;
    };
    AccountReorderInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AccountReorderInputBody.json
       */
      readonly $schema?: string;
      /** @description 按目标顺序排列的 account 键名单（host/username） */
      keys: string[] | null;
    };
    AccountSaveInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AccountSaveInputBody.json
       */
      readonly $schema?: string;
      /** @description 所属 forge host（唯一键之一） */
      forgeHost: string;
      /** @description API token；提交掩码值视为未修改 */
      token?: string;
      /** @description 平台用户名（唯一键之一） */
      username: string;
    };
    AcctMeta: {
      /** Format: date-time */
      fetchedAt: string;
      forgeHost: string;
      /** Format: int64 */
      repoCount: number;
      username: string;
    };
    BranchAddRequest: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/BranchAddRequest.json
       */
      readonly $schema?: string;
      branch: string;
      commitish?: string;
      path: string;
    };
    BranchDeleteRequest: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/BranchDeleteRequest.json
       */
      readonly $schema?: string;
      branch: string;
      force?: boolean;
      path: string;
    };
    CloneRule: {
      localPath: string;
      repoHost: string;
      repoPrefix: string;
    };
    CloneRuleDeleteInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CloneRuleDeleteInputBody.json
       */
      readonly $schema?: string;
      /** @description 规则键：源域名 */
      repoHost: string;
      /** @description 规则键：uri 前缀 */
      repoPrefix: string;
    };
    CloneRuleKey: {
      repoHost: string;
      repoPrefix: string;
    };
    CloneRuleReorderInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CloneRuleReorderInputBody.json
       */
      readonly $schema?: string;
      /** @description 按目标顺序排列的 host+prefix 名单 */
      rules: components['schemas']['CloneRuleKey'][] | null;
    };
    CloneRuleSaveInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CloneRuleSaveInputBody.json
       */
      readonly $schema?: string;
      /** @description 对应本地目录（绝对路径或 ~/ 前缀） */
      localPath: string;
      /** @description 源域名，无协议，如 github.com */
      repoHost: string;
      /** @description uri 前缀，须以 / 开头或为空，如 /heyuuu */
      repoPrefix?: string;
    };
    CommitDetail: {
      author: string;
      body: string;
      parents: string[] | null;
      refs: components['schemas']['CommitRef'][] | null;
      sha: string;
      shortSha: string;
      subject: string;
      /** Format: int64 */
      timestamp: number;
    };
    CommitEntry: {
      author: string;
      parents: string[] | null;
      refs: components['schemas']['CommitRef'][] | null;
      sha: string;
      shortSha: string;
      subject: string;
      /** Format: int64 */
      timestamp: number;
    };
    CommitRef: {
      kind: string;
      name: string;
    };
    CommitsPageResult: {
      hasMore: boolean;
      list: components['schemas']['CommitEntry'][] | null;
      /** Format: int64 */
      nextCursor: number;
    };
    Config: {
      create: components['schemas']['CreateConfig'];
      dataDir: string;
      log: components['schemas']['LogConfig'];
      server: components['schemas']['ServerConfig'];
    };
    CreateConfig: {
      templateSource: string;
    };
    DiffEntry: {
      /** Format: int64 */
      adds: number;
      binary: boolean;
      /** Format: int64 */
      dels: number;
      oldPath: string;
      path: string;
      status: string;
    };
    DiffLine: {
      kind: string;
      text: string;
    };
    DiffTreesResult: {
      list: components['schemas']['DiffEntry'][] | null;
      mode: string;
    };
    Entry: {
      /** Format: int64 */
      ahead: number;
      /** Format: int64 */
      behind: number;
      branches: string[] | null;
      /** Format: date-time */
      collectedAt: string;
      currentBranch: string;
      defaultBranch: string;
      dirty: boolean;
      remotes: components['schemas']['RemoteInfo'][] | null;
      repoUrl: string;
      workspaces: components['schemas']['Workspace'][] | null;
      worktrees: components['schemas']['WorktreeInfo'][] | null;
    };
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string;
      /** @description Error message text */
      message?: string;
      /** @description The value at the given location */
      value?: unknown;
    };
    ErrorModel: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ErrorModel.json
       */
      readonly $schema?: string;
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string;
      /** @description Optional list of individual error details */
      errors?: components['schemas']['ErrorDetail'][] | null;
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string;
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number;
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string;
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string;
    };
    FileDiffResult: {
      binary: boolean;
      hunks: components['schemas']['Hunk'][] | null;
    };
    FileResult: {
      binary: boolean;
      content: string;
      deleted: boolean;
      /** Format: int64 */
      size: number;
    };
    FileSaveRequest: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/FileSaveRequest.json
       */
      readonly $schema?: string;
      content: string;
      file: string;
      path: string;
      source: string;
    };
    Forge: {
      host: string;
      icon?: components['schemas']['Icon'];
      kind: string;
    };
    ForgeDeleteInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ForgeDeleteInputBody.json
       */
      readonly $schema?: string;
      /** @description 规则唯一键 */
      host: string;
    };
    ForgeReorderInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ForgeReorderInputBody.json
       */
      readonly $schema?: string;
      /** @description 按目标顺序排列的 host 名单 */
      hosts: string[] | null;
    };
    ForgeSaveInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ForgeSaveInputBody.json
       */
      readonly $schema?: string;
      /** @description 域名（可带端口），如 github.com */
      host: string;
      /** @description 平台图标（可选：lucide 图名或 base64 PNG） */
      icon?: components['schemas']['IconDTO'];
      /** @description API 方言：github / gitea / gitee / generic */
      kind: string;
    };
    Hunk: {
      lines: components['schemas']['DiffLine'][] | null;
      /** Format: int64 */
      newCount: number;
      /** Format: int64 */
      newStart: number;
      /** Format: int64 */
      oldCount: number;
      /** Format: int64 */
      oldStart: number;
    };
    Icon: {
      type: string;
      value: string;
    };
    IconDTO: {
      type: string;
      value: string;
    };
    IconExtractInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/IconExtractInputBody.json
       */
      readonly $schema?: string;
      /** @description 图标来源：本地路径（.app 目录或图片文件）或 http(s) URL（如 https://gitee.com/favicon.ico） */
      source: string;
    };
    IconExtractResult: {
      /** @description 64px PNG 的 base64 字符串 */
      value: string;
    };
    Info: {
      defaultBranch: string;
      root: string;
    };
    IntentDefaultDeleteInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/IntentDefaultDeleteInputBody.json
       */
      readonly $schema?: string;
      /** @description 打开意图 */
      intent: string;
    };
    IntentDefaultSaveInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/IntentDefaultSaveInputBody.json
       */
      readonly $schema?: string;
      /** @description 打开意图（如 dir / file / diff-file / git） */
      intent: string;
      /** @description opener 名称（须声明该 intent 对应的 role） */
      opener: string;
    };
    JsonOutputCommitDetailBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputCommitDetailBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['CommitDetail'];
      message: string;
      ok: boolean;
    };
    JsonOutputCommitsPageResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputCommitsPageResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['CommitsPageResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputConfigBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputConfigBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['Config'];
      message: string;
      ok: boolean;
    };
    JsonOutputDiffTreesResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputDiffTreesResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['DiffTreesResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputFileDiffResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputFileDiffResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['FileDiffResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputFileResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputFileResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['FileResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputIconExtractResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputIconExtractResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['IconExtractResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputInfoBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputInfoBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['Info'];
      message: string;
      ok: boolean;
    };
    JsonOutputListRemoteEntryBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputListRemoteEntryBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['RemoteEntry'][] | null;
      message: string;
      ok: boolean;
    };
    JsonOutputListResultAccountBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputListResultAccountBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultAccount'];
      message: string;
      ok: boolean;
    };
    JsonOutputListResultCloneRuleBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputListResultCloneRuleBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultCloneRule'];
      message: string;
      ok: boolean;
    };
    JsonOutputListResultForgeBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputListResultForgeBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultForge'];
      message: string;
      ok: boolean;
    };
    JsonOutputListResultOpenerDTOBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputListResultOpenerDTOBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultOpenerDTO'];
      message: string;
      ok: boolean;
    };
    JsonOutputListResultOpenerIntentDTOBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputListResultOpenerIntentDTOBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultOpenerIntentDTO'];
      message: string;
      ok: boolean;
    };
    JsonOutputListResultPathUsageBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputListResultPathUsageBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultPathUsage'];
      message: string;
      ok: boolean;
    };
    JsonOutputListResultScanRuleBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputListResultScanRuleBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ListResultScanRule'];
      message: string;
      ok: boolean;
    };
    JsonOutputListWorktreeStatusBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputListWorktreeStatusBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['WorktreeStatus'][] | null;
      message: string;
      ok: boolean;
    };
    'JsonOutputMapStringInterface {}Body': {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputMapStringInterface {}Body.json
       */
      readonly $schema?: string;
      data: {
        [key: string]: unknown;
      };
      message: string;
      ok: boolean;
    };
    JsonOutputMdContentResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputMdContentResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['MdContentResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputMdListResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputMdListResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['MdListResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputOverviewBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputOverviewBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['Overview'];
      message: string;
      ok: boolean;
    };
    JsonOutputProjectListResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputProjectListResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['ProjectListResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputRefsBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputRefsBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['Refs'];
      message: string;
      ok: boolean;
    };
    JsonOutputTreeListResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputTreeListResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['TreeListResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputWhoamiResponseBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputWhoamiResponseBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['WhoamiResponse'];
      message: string;
      ok: boolean;
    };
    JsonOutputWorkspaceStateResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputWorkspaceStateResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['WorkspaceStateResult'];
      message: string;
      ok: boolean;
    };
    JsonOutputWorktreeCreatedBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputWorktreeCreatedBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['WorktreeCreated'];
      message: string;
      ok: boolean;
    };
    JsonOutputWorktreeRemoveResultBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/JsonOutputWorktreeRemoveResultBody.json
       */
      readonly $schema?: string;
      data: components['schemas']['WorktreeRemoveResult'];
      message: string;
      ok: boolean;
    };
    ListResultAccount: {
      list: components['schemas']['Account'][] | null;
    };
    ListResultCloneRule: {
      list: components['schemas']['CloneRule'][] | null;
    };
    ListResultForge: {
      list: components['schemas']['Forge'][] | null;
    };
    ListResultOpenerDTO: {
      list: components['schemas']['OpenerDTO'][] | null;
    };
    ListResultOpenerIntentDTO: {
      list: components['schemas']['OpenerIntentDTO'][] | null;
    };
    ListResultPathUsage: {
      list: components['schemas']['PathUsage'][] | null;
    };
    ListResultScanRule: {
      list: components['schemas']['ScanRule'][] | null;
    };
    LocalRepo: {
      /** Format: int64 */
      ahead: number;
      /** Format: int64 */
      behind: number;
      dirty: boolean;
      name: string;
      path: string;
      repoUrl: string;
    };
    LogConfig: {
      format: string;
      level: string;
      path: string;
    };
    MdContentResult: {
      content: string;
    };
    MdListResult: {
      dir: boolean;
      files: string[] | null;
    };
    OpenerDTO: {
      actions: {
        [key: string]: string;
      };
      icon: components['schemas']['IconDTO'];
      name: string;
      summary: string;
      title: string;
    };
    OpenerDeleteInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OpenerDeleteInputBody.json
       */
      readonly $schema?: string;
      /** @description opener 名称 */
      name: string;
    };
    OpenerDiffOpenInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OpenerDiffOpenInputBody.json
       */
      readonly $schema?: string;
      /** @description 左侧路径（文件或目录）绝对路径 */
      left: string;
      /** @description opener 名称 */
      opener: string;
      /** @description 右侧路径（文件或目录）绝对路径 */
      right: string;
    };
    OpenerIntentDTO: {
      defaultOpener?: string;
      intent: string;
      openers: string[] | null;
    };
    OpenerOpenInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OpenerOpenInputBody.json
       */
      readonly $schema?: string;
      /** @description opener 名称 */
      opener: string;
      /** @description 文件或目录绝对路径 */
      path: string;
    };
    OpenerReorderInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OpenerReorderInputBody.json
       */
      readonly $schema?: string;
      /** @description 按目标顺序排列的 opener 名单 */
      names: string[] | null;
    };
    OpenerSaveInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/OpenerSaveInputBody.json
       */
      readonly $schema?: string;
      /** @description role → 动作串，exec: 命令 / url: 链接，$0/$1 占位路径槽位 */
      actions: {
        [key: string]: string;
      };
      /** @description 图标声明 */
      icon?: components['schemas']['IconDTO'];
      /** @description opener 名称（唯一标识） */
      name: string;
      /** @description 展示文案（如「打开所在目录」），缺省由 name 生成 */
      title?: string;
    };
    Overview: {
      accounts: components['schemas']['AcctMeta'][] | null;
      rows: components['schemas']['RepoRow'][] | null;
    };
    PathUsage: {
      path: string;
      /** Format: date-time */
      time: string;
    };
    ProjectDTO: {
      gitInfo: components['schemas']['Entry'];
      group: string;
      /** Format: date-time */
      lastUsedAt?: string;
      name: string;
      path: string;
      tags: string[] | null;
    };
    ProjectListResult: {
      /** Format: date-time */
      gitUpdatedAt: string;
      list: components['schemas']['ProjectDTO'][] | null;
      /** Format: date-time */
      scanUpdatedAt: string;
    };
    ProjectOpenInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ProjectOpenInputBody.json
       */
      readonly $schema?: string;
      /** @description 目标目录绝对路径（worktree；缺省打开项目根） */
      dir?: string;
      /** @description opener 名称 */
      opener: string;
      /** @description 项目绝对路径 */
      path: string;
    };
    Refs: {
      head: string;
      locals: string[] | null;
      remotes: string[] | null;
      tags: string[] | null;
    };
    RemoteEntry: {
      name: string;
      url: string;
      webUrl: string;
    };
    RemoteInfo: {
      name: string;
      url: string;
    };
    RemoteRepo: {
      cloneUrl: string;
      defaultBranch: string;
      fullName: string;
      name: string;
      /** Format: date-time */
      updatedAt: string;
    };
    RepoRow: {
      forgeHost: string;
      local?: components['schemas']['LocalRepo'];
      owner: string;
      repo: components['schemas']['RemoteRepo'];
      status: string;
    };
    ScanRule: {
      group: string;
      icon?: components['schemas']['Icon'];
      /** Format: int64 */
      maxDepth: number;
      path: string;
    };
    ScanRuleDeleteInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ScanRuleDeleteInputBody.json
       */
      readonly $schema?: string;
      /** @description 规则唯一键 */
      path: string;
    };
    ScanRuleReorderInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ScanRuleReorderInputBody.json
       */
      readonly $schema?: string;
      /** @description 按目标顺序排列的规则路径名单 */
      paths: string[] | null;
    };
    ScanRuleSaveInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ScanRuleSaveInputBody.json
       */
      readonly $schema?: string;
      /** @description 扫描出的项目组名 */
      group: string;
      /** @description 组图标（可选：lucide 图名或 base64 PNG） */
      icon?: components['schemas']['IconDTO'];
      /**
       * Format: int64
       * @description 扫描最大深度
       */
      maxDepth: number;
      /** @description 扫描根目录（绝对路径或 ~/ 前缀，规则唯一键） */
      path: string;
    };
    ServerConfig: {
      /** Format: int64 */
      port: number;
    };
    TreeListResult: {
      list: string[] | null;
    };
    UsageRecordInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/UsageRecordInputBody.json
       */
      readonly $schema?: string;
      /** @description 实际打开的目标目录绝对路径，缺省记项目根 */
      dir?: string;
      /** @description opener 名（web 直开的 url 型动作补记时传） */
      opener?: string;
      /** @description 项目/目录绝对路径（归并键） */
      project?: string;
    };
    WhoamiResponse: {
      app: string;
      instance: string;
      version: string;
    };
    Workspace: {
      name: string;
      path: string;
    };
    WorkspaceMemberDTO: {
      name: string;
      path: string;
    };
    WorkspaceSaveInputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/WorkspaceSaveInputBody.json
       */
      readonly $schema?: string;
      /** @description 项目绝对路径 */
      path: string;
      /** @description 显式声明的成员清单（name + 相对项目根路径） */
      workspaces: components['schemas']['WorkspaceMemberDTO'][] | null;
    };
    WorkspaceStateResult: {
      declared: components['schemas']['WorkspaceMemberDTO'][] | null;
      declaredSet: boolean;
      detected: components['schemas']['WorkspaceMemberDTO'][] | null;
      effective: components['schemas']['WorkspaceMemberDTO'][] | null;
      scanRule: string;
    };
    WorktreeAddRequest: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/WorktreeAddRequest.json
       */
      readonly $schema?: string;
      branch?: string;
      commitish?: string;
      path: string;
      targetPath?: string;
    };
    WorktreeCreated: {
      branch: string;
      detached: boolean;
      path: string;
    };
    WorktreeInfo: {
      branch: string;
      detached: boolean;
      path: string;
      workspaces: components['schemas']['Workspace'][] | null;
    };
    WorktreePruneRequest: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/WorktreePruneRequest.json
       */
      readonly $schema?: string;
      path: string;
    };
    WorktreeRemoveRequest: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/WorktreeRemoveRequest.json
       */
      readonly $schema?: string;
      force?: boolean;
      path: string;
      targetPath: string;
    };
    WorktreeRemoveResult: {
      denied: boolean;
      reasons: string[] | null;
    };
    WorktreeResetRequest: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/WorktreeResetRequest.json
       */
      readonly $schema?: string;
      hard?: boolean;
      path: string;
      target: string;
    };
    WorktreeStatus: {
      /** Format: int64 */
      ahead: number;
      bare: boolean;
      /** Format: int64 */
      behind: number;
      branch: string;
      detached: boolean;
      dirty: boolean;
      head: string;
      path: string;
      /** Format: int64 */
      staged: number;
      /** Format: int64 */
      unstaged: number;
      /** Format: int64 */
      untracked: number;
      workspaces: components['schemas']['Workspace'][] | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  'config.index': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputConfigBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.accountDelete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountDeleteInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.accountFetch': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountFetchInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.accountList': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputListResultAccountBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.accountReorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountReorderInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.accountSave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['AccountSaveInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgeDeleteInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputListResultForgeBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.overview': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputOverviewBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgeReorderInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'forge.save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ForgeSaveInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'icon.extract': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IconExtractInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputIconExtractResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'md.content': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMdContentResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'md.list': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMdListResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenerDeleteInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.diffOpen': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenerDiffOpenInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.intentDefaultDelete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IntentDefaultDeleteInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.intentDefaultSave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['IntentDefaultSaveInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.intents': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputListResultOpenerIntentDTOBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputListResultOpenerDTOBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.open': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenerOpenInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.reorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenerReorderInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'opener.save': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['OpenerSaveInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.cloneRuleDelete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CloneRuleDeleteInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.cloneRuleReorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CloneRuleReorderInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.cloneRuleSave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CloneRuleSaveInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.cloneRules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputListResultCloneRuleBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.list': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputProjectListResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.open': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ProjectOpenInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.scanRuleDelete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScanRuleDeleteInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.scanRuleReorder': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScanRuleReorderInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.scanRuleSave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ScanRuleSaveInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.scanRules': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputListResultScanRuleBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.workspaceGet': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputWorkspaceStateResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'project.workspaceSave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorkspaceSaveInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'system.whoami': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputWhoamiResponseBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'usage.recentPaths': {
    parameters: {
      query?: {
        /** @description 返回条数上限，缺省 5 */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputListResultPathUsageBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'usage.record': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UsageRecordInputBody'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.branchAdd': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BranchAddRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.branchDelete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['BranchDeleteRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.changes': {
    parameters: {
      query: {
        path: string;
        source: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputDiffTreesResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.commit': {
    parameters: {
      query: {
        path: string;
        source: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputCommitDetailBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.commits': {
    parameters: {
      query: {
        path: string;
        cursor?: number;
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputCommitsPageResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.diff': {
    parameters: {
      query: {
        path: string;
        base: string;
        current: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputDiffTreesResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.file': {
    parameters: {
      query: {
        path: string;
        source: string;
        file: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputFileResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.fileDiff': {
    parameters: {
      query: {
        path: string;
        base?: string;
        current: string;
        file: string;
        baseFile?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputFileDiffResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.fileRaw': {
    parameters: {
      query: {
        source: string;
        path: string;
        file: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          'Cache-Control'?: string;
          'Content-Type'?: string;
          [name: string]: unknown;
        };
        content: {
          'application/json': string;
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.fileSave': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FileSaveRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputFileResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.info': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputInfoBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.refs': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputRefsBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.remotes': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputListRemoteEntryBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.tree': {
    parameters: {
      query: {
        path: string;
        source: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputTreeListResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.worktreeAdd': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorktreeAddRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputWorktreeCreatedBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.worktreePrune': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorktreePruneRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.worktreeRemove': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorktreeRemoveRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputWorktreeRemoveResultBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.worktreeReset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['WorktreeResetRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputMapStringInterface {}Body'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
  'workbench.worktrees': {
    parameters: {
      query: {
        path: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description OK */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['JsonOutputListWorktreeStatusBody'];
        };
      };
      /** @description Error */
      default: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['ErrorModel'];
        };
      };
    };
  };
}
