// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/heyuuu/cube/config"
	"github.com/heyuuu/cube/history"
	"github.com/heyuuu/cube/opener"
	"github.com/heyuuu/cube/project"
	"github.com/heyuuu/cube/web"
)

// Injectors from wire.go:

func InitApp() *App {
	configConfig := config.Default()
	configService := config.NewConfigService(configConfig)
	configHandler := web.NewConfigHandler(configService)
	workspaceService := project.NewWorkspaceService(configConfig)
	workspaceHandler := web.NewWorkspaceHandler(workspaceService)
	projectService := project.NewProjectService(workspaceService)
	projectHandler := web.NewProjectHandler(projectService)
	applicationService := opener.NewApplicationService(configConfig)
	applicationHandler := web.NewApplicationHandler(applicationService)
	remoteService := project.NewRemoteService(configConfig)
	remoteHandler := web.NewRemoteHandler(remoteService)
	v := web.AllHandlers(configHandler, workspaceHandler, projectHandler, applicationHandler, remoteHandler)
	server := web.NewServer(v)
	historyService := history.NewHistoryService()
	app := &App{
		server:             server,
		workspaceService:   workspaceService,
		projectService:     projectService,
		applicationService: applicationService,
		remoteService:      remoteService,
		historyService:     historyService,
	}
	return app
}
