// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/heyuuu/cube/config"
	handlers2 "github.com/heyuuu/cube/handlers"
	"github.com/heyuuu/cube/server"
	services2 "github.com/heyuuu/cube/services"
)

// Injectors from wire.go:

func InitApp() *App {
	configConfig := config.Default()
	configService := services2.NewConfigService(configConfig)
	configHandler := handlers2.NewConfigHandler(configService)
	workspaceService := services2.NewWorkspaceService(configConfig)
	workspaceHandler := handlers2.NewWorkspaceHandler(workspaceService)
	projectService := services2.NewProjectService(workspaceService)
	projectHandler := handlers2.NewProjectHandler(projectService)
	applicationService := services2.NewApplicationService(configConfig)
	applicationHandler := handlers2.NewApplicationHandler(applicationService)
	remoteService := services2.NewRemoteService(configConfig)
	remoteHandler := handlers2.NewRemoteHandler(remoteService)
	v := handlers2.AllHandlers(configHandler, workspaceHandler, projectHandler, applicationHandler, remoteHandler)
	serverServer := server.NewServer(v)
	historyService := services2.NewHistoryService()
	app := &App{
		server:             serverServer,
		workspaceService:   workspaceService,
		projectService:     projectService,
		applicationService: applicationService,
		remoteService:      remoteService,
		historyService:     historyService,
	}
	return app
}
